server:
  port: 8088
spring:
  profiles:
    active: after_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://47.105.192.33:8080
        predicates:
        - Path=/eureka/{d}
  profiles: after_route
