server:
  port: 8085
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hello:
      path: /hello/**
      serviceId: hello-service
    hello1:
      path: /hello1/**
      serviceId: consumer
